# Generated by Django 5.2.6 on 2025-09-30 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedpdf',
            old_name='indexed',
            new_name='is_indexed',
        ),
    ]
